INCLUDES_DREAMLAND = \
-I$(top_srcdir)/libdreamland \
-I$(top_srcdir)/libdreamland/regex \
-I$(top_srcdir)/libdreamland/lang \
-I$(top_srcdir)/libdreamland/util \
-I$(top_srcdir)/libdreamland/xml \
-I$(top_srcdir)/libdreamland/plugin \
-I$(top_srcdir)/libdreamland/scheduler \
-I$(top_srcdir)/libdreamland/io \
-I$(top_srcdir)/libdreamland/fenia \
-I$(top_srcdir)/libdreamland/l10n \
-I$(top_srcdir)/libdreamland/alloc \
-I$(top_srcdir)/libdreamland/flags \
-I$(top_srcdir)/libdreamland/gref \
-I$(top_srcdir)/libdreamland/process 

