#ifndef PARSER_ID_H
#define PARSER_ID_H
/* Файл описывает индефикаторы TYPE_LIST и TYPE_VECTOR */

/* [LIST] */
#define LIST_HELP_TYPES  1
#define LIST_MAT_TYPES  2
#define LIST_RESET_TYPES 3
#define LIST_PLANE_TYPES 4
#define LIST_DISTRICT_TYPES 5
#define LIST_DIRECTIONS  6
#define LIST_EXIT_TYPES  7
#define LIST_PORTAL_TYPES 8
#define LIST_COMMANDS  9
#define LIST_DAMAGE_TYPES 10
#define LIST_SEX  11
#define LIST_OBJ_TYPES  12
#define LIST_CLASS  13
#define LIST_RACE  14
#define LIST_POSITIONS  15
#define LIST_MOB_MOVE  16
#define LIST_SKILLS  17
#define LIST_SPELLS  18
#define LIST_EQ_POS  19
#define LIST_SAVE_TYPES  20
#define LIST_MOB_HIT  21
#define LIST_MOB_SPEC_TYPE 22
#define LIST_APPLY  23
#define LIST_MATERIAL_TYPE 24
#define LIST_WEAPON_SKILLS 25
#define LIST_WEAPON_TYPE 26
#define LIST_LIQUID_TYPE 27
#define LIST_GODS  28
#define LIST_SPH_TYPES  29
#define LIST_YESNO  30
#define LIST_TRAP_TYPE  31
#define LIST_FRACTION  32
#define LIST_RANK  33
#define LIST_TYPE_WEAPON 34
#define LIST_PTYPE_WEAPON 35
#define LIST_ZONE_TYPE  36
#define LIST_TARGET  37
#define LIST_TYPE_ARMOR  39
#define LIST_PTYPE_ARMOR 40
#define LIST_DAMAGE  41
#define LIST_RENT_TYPES  42
#define LIST_TYPE_ACLASS 43
#define LIST_BODY_POSITION 47
#define LIST_BODY_NAME  48
#define LIST_MOB_TYPE  49
#define LIST_TOOLS  50
#define LIST_ANSWER  51
#define LIST_AGE  52
#define LIST_MISSILE  53
#define LIST_WEATHER  54
#define LIST_WARD_TYPES  55
#define LIST_ENCHANT  56
#define LIST_EXP_TYPE  57
#define LIST_EVENTS  58

/* [VECTOR] */
#define VEC_PROP_ROOM  1
#define VEC_EXIT_PROP  2
#define VEC_MOB_PROP  3
#define VEC_MOB_ADDS  4
#define VEC_ANTI  5
#define VEC_OBJ_PROP  6
#define VEC_OBJ_WEAR  7
#define VEC_SPELL_TARGET 8
#define VEC_TRAP_TYPE  9
#define VEC_AGRO_TYPE  10
#define VEC_TRANS_PROP  11
#define VEC_MOB_AFF  12
#define VEC_MOB_SPEC  13

#endif
